CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev
# SERVER
MYSQL_HOST: localhost
#MYSQL_PORT: 5432
MYSQL_PORT: 3306
MYSQL_DATABASE: 
MYSQL_PASSWORD: 
MYSQL_USERNAME: 
# EMAIL HOST
EMAIL_HOST: 
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD: 
# URL VERIFY
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}
UI_API_URL: http://localhost:4200
JWT_SECRET: myverysecuresecert

# JWT_EXPIRATION: 432_000_000
# JWT_SECRET: ${SECRET}
