CONTAINER_PORT: 8080
ACTIVE_PROFILE: test
# SERVER
MYSQL_HOST: localhost
#MYSQL_PORT: 5432
MYSQL_PORT: 3306
MYSQL_DATABASE: secureintelligence
MYSQL_PASSWORD: lmk9a3dc
MYSQL_USERNAME: austine
# EMAIL HOST
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: austineyoyogie@gmail.com
EMAIL_PASSWORD: geuayaruryudccjr
# URL VERIFY
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}
UI_API_URL: http://localhost:4200
JWT_SECRET: myverysecuresecert


